### ISSUE TITLE
Include time in /api/pipelines reply

### ISSUE THREAD

**Issue by zbal** [Wiredcraft/pipelines#10]
Either we include the time in the `/api/pipelines` response for the various runs, or we don't but implicitly sort the runs per time (start / end). But we need some way to know what are the latest runs.

see #9

**Comment by JuhaS** [comment]
We talked with xavier to use folder creation times for that, but is we have the time in json it sounds cleaner.

**Comment by JuhaS** [comment]
Timestamps are now included in the `/api/pipelines` response but backend does not sort the list.

**Comment by JuhaS** [comment]
Closing, runs are sorted by runtime.
