### ISSUE TITLE
Update from deprecated usage of access_token for GitHub API

### ISSUE THREAD

**Issue by JuhaS** [Wiredcraft/pipelines#108]
Github is deprecating sending access_token as part of querystring, it should be included as "Autorization" header instead. 

Reference:
https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters

This line needs to change and instead add it as a header: https://github.com/Wiredcraft/pipelines/blob/dev/pipelines/api/ghauth.py#L122

**Comment by kaleocheng** [comment]
closing as done
