### ISSUE TITLE
`Bash` type bug 

### ISSUE THREAD

**Issue by guinan34** [Wiredcraft/pipelines#141]
when using `Bash` type in pipeline as an action task. if the shell returned an exit code . such as 3 or 4 or others.  the pipeline will returned an error as below first screenshot shown  . 
i checked the source code found the the bash module exception handle section has some issues need to fix. 

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/16395409/172119599-64272395-2221-4bdc-9d97-4f8eaebc6e7e.png">
<img width="781" alt="image" src="https://user-images.githubusercontent.com/16395409/172119215-27b494c5-983e-4766-b75a-9a8cf3e5980e.png">

**Comment by sp3c73r2038** [comment]
https://github.com/amoffat/sh/blob/1.14.2/sh.py#L337-L399
as you can see, ErrorReturnCode only has `full_cmd/stdout/stderr/truncate` properties. it should use `str(e)` here.

and e.exit_code  do exist when the exception is an instance of  ErrorReturnCode_${exit_code} like `ErrorReturnCode_4`  in this case.

I think it will be a easy fix if you're interested.
