### ISSUE TITLE
UI: Pipelines logo V1

### ISSUE THREAD

**Issue by hopechen1028** [Wiredcraft/pipelines#29]
Based on Ronan's inspiration: character "P" + "play button", I created an initial version of the logo for Pipelines.

![pipeline-logo](https://cloud.githubusercontent.com/assets/19304091/20094764/b15bd8a4-a5dd-11e6-8841-e1334f065b39.jpg)

@hunvreus @z4rd @Iriszhousy   give me your feedbacks plz~~~ 🐰🐰

**Comment by makara** [comment]
Hey that reminds me this: https://en.wikipedia.org/wiki/M%C3%B6bius_strip

**Comment by hopechen1028** [comment]
yup=_= nowadays all the logos with weird shape get inspiration from mobius ring, but I only add one angle :p


On 11/08/2016 20:23, Makara Wang wrote:

Hey that reminds me this: https://en.wikipedia.org/wiki/M%C3%B6bius_strip

**Comment by hopechen1028** [comment]
![pipeline-logo-1](https://cloud.githubusercontent.com/assets/19304091/20127284/f4bfbc42-a677-11e6-92f3-c15304edf277.jpg)
[pipelines-logo-v1.1.ai.zip](https://github.com/Wiredcraft/pipelines/files/579944/pipelines-logo-v1.1.ai.zip)


Update few details, fix the width of two round corners

**Comment by JuhaS** [comment]
@hopechen1028 can you give one for favicon?

**Comment by hopechen1028** [comment]
[favicons.zip](https://github.com/Wiredcraft/pipelines/files/582480/favicons.zip)
```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="theme-color" content="#ffffff">```

@JuhaS  Here it is
