### ISSUE TITLE
GitHub authentication

### ISSUE THREAD

**Issue by JuhaS** [Wiredcraft/pipelines#36]
We are adding a GitHub OAuth authentication. User can select teams that are allowed to access the UI.

Command line argument: `--github-auth=Acme/Team1,Acme/Team2`

If user does not belong to allowed teams he gets redirected back to login page.

**Comment by JuhaS** [comment]
Need to review the Github Oauth and add docs.

**Comment by kaleocheng** [comment]
closing as done
