### ISSUE TITLE
Empty value in prompt cause pipelines display no tasks

### ISSUE THREAD

**Issue by xuqingfeng** [Wiredcraft/pipelines#38]
```yaml
---
prompt:
  key:

actions:
  - echo {{ key }}
```

**Comment by JuhaS** [comment]
I added pipeline validation when the UI loads, so now you should see an error that null is not allowed, you'll have to use `key: ""` instead.

UI will look like:
![image](https://user-images.githubusercontent.com/919180/27319265-1c0ebb72-55c3-11e7-9520-63ff778fd940.png)

**Comment by xuqingfeng** [comment]
Close as fixed.
