### ISSUE TITLE
webhook interface for run pipelines

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/pipelines#5]
- [ ] An API to generate webhook url with slug id
- [ ] An processor(route handler) for transforming the webhook url to pipeline and run it.

The first step is using some light approaches such as yaml files to implement it instead of  DB.

**Comment by hunvreus** [comment]
Isn't that simply a publicly accessible endpoint for each pipeline (random hash like `wh/xj39dkqp14lsdf03lsdf`) that triggers it? This was the webhooks we had for devo.ps (obviously we were using subdomains):

<img width="777" alt="screenshot at may 20 16-59-28" src="https://cloud.githubusercontent.com/assets/306868/15422697/5805d0b0-1eac-11e6-8afc-baced996be10.png">

**Comment by xavierchow** [comment]
Just don't want to use one publicly url for each pipeline everywhere, and it's better to be generated on demand.

**Comment by hunvreus** [comment]
For now a simple `wk/name-of-the-pipeline` would be enough. We can then hash it later on to `wk/something-super-hard-to-guess-like-a-hash`

**Comment by JuhaS** [comment]
The webhook PR was merged with some modifications, testing it now.

**Comment by JuhaS** [comment]
Working, done.
