### ISSUE TITLE
duplicated readme at app

### ISSUE THREAD

**Issue by paulvollmer** [Wiredcraft/pipelines#50]
https://github.com/Wiredcraft/pipelines/blob/dev/app/readme.md
https://github.com/Wiredcraft/pipelines/blob/dev/app/readme.md2

**Comment by JuhaS** [comment]
Fixed in [3957dbf](https://github.com/Wiredcraft/pipelines/commit/3957dbfd94f7aa40a196c2d9a3e2552abeb63457). Closing, thanks for raising it up @paulvollmer.
