### ISSUE TITLE
Fix error handling on template errors

### ISSUE THREAD

**Issue by JuhaS** [Wiredcraft/pipelines#55]
We changed the templating to use Jinja2 so it will throw Jinja errors now. We should update the error handling code [here](https://github.com/Wiredcraft/pipelines/blob/dev/pipelines/pipeline/pipeline.py#L177) to catch a jinja base error class (if possible).

**Comment by zbal** [comment]
FYI - exceptions raised are: http://jinja.pocoo.org/docs/2.9/api/#exceptions

Can catch `TemplateError` for a first try, and we'll refine later what the issue is (bad template, bad var, bad, etc.). For the moment we simply fail the task and report an error.

**Comment by zbal** [comment]
Pushed as 7b22a0a
