### ISSUE TITLE
API freeze when task do not complete

### ISSUE THREAD

**Issue by zbal** [Wiredcraft/pipelines#62]
The api freeze in some condition, typically when tasks ran but never complete...

Killing the tasks (via `ps aux` and `kill`) effectively "release" the API, and the operation resumes.

See below some sample of the logs - notice that the process was "stuck" for quite a long time, then I killed the processes at the time the `BashExec failed` messages appears.

```
2017-03-22 08:35:02,201 - DEBUG - Getting pipeline logs
2017-03-23 01:17:01,650 - DEBUG - BashExec failed
2017-03-23 01:17:01,651 - DEBUG - BashExec failed
2017-03-23 01:17:01,652 - DEBUG - Task finished. Result: {'status': 1, 'message': 'Bash task finished'}
2017-03-23 01:17:01,652 - DEBUG - Skipping task: Update local code base
2017-03-23 01:17:01,652 - DEBUG - Skipping task: Deploy updated container
2017-03-23 01:17:01,653 - DEBUG - Skipping task: Send slack notification
2017-03-23 01:17:01,653 - DEBUG - Pipeline finished. Status: failure
```

/cc @JuhaS @xuqingfeng

**Comment by zbal** [comment]
Caused by: https://github.com/Wiredcraft/pipelines/blob/dev/pipelines/api/server.py#L69

Approaches:
- add timeout on tasks
- add dedicated thread to maintain the API up and running despite the workers being stucked

@JuhaS - are the threads being handling the pipelines? or the tasks?

**Comment by zbal** [comment]
Had again the issue - it seems to be related in fact with the reading of logs - that could be "breaking" the server ...

https://github.com/Wiredcraft/pipelines/blob/dev/pipelines/api/server.py#L380-L387

Wondering if a bad file would block the process...

**Comment by JuhaS** [comment]
Probably because we don't currently close a file after every line: https://github.com/Wiredcraft/pipelines/blob/dev/pipelines/plugins/bash_executor.py#L64

We should probably open/close it after every line (not sure of the speed though).

**Comment by zbal** [comment]
Yet another likely root cause: https://github.com/docker/docker/issues/30405 -- when running pipelines in a container, when there is barely no network traffic, the 1st REQ through an nginx will often be welcomed with a 502 ... 

This could be alleviated by using a reverse proxy that enables some HTTP health check to "force" some traffic to occur. (e.g. `haproxy` or `openresty`)

**Comment by JuhaS** [comment]
@zbal is there something we can do to prevent or detect this? Should we close this issue?

**Comment by zbal** [comment]
Closing - this is not a pipelines related issue.
