### ISSUE TITLE
Support pipeline as code

### ISSUE THREAD

**Issue by EcutDavid** [Wiredcraft/pipelines#63]
Hi, recently I'm playing with Jenkins and found their `pipeline as code` feature very helpful.

I can pull the pipeline configuration from remote repo.
![image](https://cloud.githubusercontent.com/assets/10692276/24825027/d79eaae6-1c48-11e7-9f87-fb3a56855dc4.png)
Or edit it in the UI:
![image](https://cloud.githubusercontent.com/assets/10692276/24825037/29bd59da-1c49-11e7-8ca9-bf632c883458.png)

This is my simplest Jenkins pipeline configuration code: https://github.com/EcutDavid/react-resetcss-dev-template/blob/master/Jenkinsfile

So what about support:
Define the configuration yaml URL in front end, and pull it periodically into workspace.   
Or other better solutions?

**Comment by hunvreus** [comment]
We've been discussing being able to fetch pipelines from a remote source (starting with Git) as well as allowing us to edit pipelines directly through the interface. It's on our roadmap for the next couple releases.

**Comment by JuhaS** [comment]
I was thinking this, one possible solution:
- You choose Github OAuth as login option (so we get token to access your repos)
- When you first login we clone the repo and set the workspace folder to point to the `/pipelines` (or whatever folder you choose).
- We have a "resync with git" button that will refetch the git-repo.

**Comment by hunvreus** [comment]
@JuhaS Is the GitHub log in working already? It'd be nice to activate it at least for one project.

**Comment by JuhaS** [comment]
>  Is the GitHub log in working already?

Yes, but probably needs some cleanup, I'll try to make that happen this week.
