### ISSUE TITLE
Is there a way to set the timezone for pipelines?

### ISSUE THREAD

**Issue by JonLundy** [Wiredcraft/pipelines#64]
The server that is running pipelines is running with UTC time. when i view tasks in the web front end it tells me the tasks were completed X hours in the future.

**Comment by JuhaS** [comment]
Hi @JonLundy, thanks for helping make pipelines better! Timezone management is currently not configurable and is one of the next improvements we want to make. #57 is an implementation issue for adding this.

**Comment by JuhaS** [comment]
Closing this one, this issue is being addressed in #57, I just pushed a PR for it.
