### ISSUE TITLE
Limit size of input parameter logs

### ISSUE THREAD

**Issue by JuhaS** [Wiredcraft/pipelines#69]
__Problem__
Currently we print the whole webhook content at the start of the pipeline. This leads to very verbose logs in case of github webhooks (content is long) and making the logs less usable in general.

Log format:
```
Pipeline started. vars: .....(n+1 pages of content after this)
```

__Solution__

I will probably add a limit on the log  length of the webhook content to 800 characters.

@zbal making this high prio since it affects current UX in current projects.

**Comment by zbal** [comment]
I wouldn't shrink it per se - as the data are valuable.

Instead I'd format the log file, and potentially start with a `yaml` frontmatter with those meta data; then having the raw logs. 

This way we can process it more easily in the client and have various options to format the headers vs. display the raw output as we are doing now

**Comment by JuhaS** [comment]
Implemented:
- highlighting on keys
- yaml format the values
- limit any single value to 3000 characters (defined as variable in stdout_logger.py
- remove the ['webhook_content']['raw'] from logs

Screenshot of the result (used 100character maximum for testing here):
![image](https://user-images.githubusercontent.com/919180/27211962-7098d3a8-528f-11e7-9ff7-5a85cd27d7d6.png)

@zbal assigned the PR to you: https://github.com/Wiredcraft/pipelines/pull/70
