### ISSUE TITLE
Pipelines will mark a task as failed if the word error is displayed anywhere in the log. 

### ISSUE THREAD

**Issue by JonLundy** [Wiredcraft/pipelines#74]
I have a script that outputs some text which contains the word error as part of an informational string. this marks the entire process as failed. 

how can i work around this? is there a variable i can set to ignore log output and trust only the exit code?

**Comment by JuhaS** [comment]
> I have a script that outputs some text which contains the word error as part of an informational string. this marks the entire process as failed.

Hi, @JonLundy. The log  processing is purely superficial to assist highlighting certain words, it does not affect the pipeline or action status. There might be some other underlying problem in your pipeline. If you want help debugging, feel free to paste your pipeline or logs here.
