### ISSUE TITLE
Add icons/update UI title

### ISSUE THREAD

**Issue by zbal** [Wiredcraft/pipelines#85]
I got a whole bunch of `pipelines` setup - but they are all the same look & feel.

Can we;
- specify a custom icon?
- tune the title?

See example; 5 completely different setups on misc domains - very hard to distinguish.

<img width="1232" alt="screen shot 2018-03-23 at 09 26 06" src="https://user-images.githubusercontent.com/631984/37806748-935e3378-2e7c-11e8-8eb2-02d1276929d9.png">

**Comment by hunvreus** [comment]
I think what we should do is allow for a custom title and a custom color, but keep the same favicon for every one of them (just change the background color).

**Comment by kaleocheng** [comment]
closing as done
