### ISSUE TITLE
Include time in status.json

### ISSUE THREAD

**Issue by zbal** [Wiredcraft/pipelines#9]
Need to include various time details in the status:
- pipeline's start / end time
- pipeline's task start / end time

**Comment by JuhaS** [comment]
The pipeline state/finish date are there now, @zbal should we still add the task times?

Current:
```json
{
  "status": "failure", 
  "finish_time": "2016-10-27T15:20:31.029010", 
  "start_time": "2016-10-27T15:20:30.822568"
}
```
